### PR TITLE
TrackRowInfoVisComparison component

### LINKED ISSUE #269: Sometimes interval query does not work
Cliff said, it is sometimes not possible to make a request for Search-By-Interval query after selecting a genomic region.

### PR DESCRIPTION
**Pull request by keller-mark**
Fixes #269

### CODE REVIEW

File: src/ViewColumnBrush.js [hunk 1]
```diff
@@ -27,6 +27,7 @@ export default function ViewColumnBrush(props) {
         onRequestIntervalTFs
     } = props;
 
+    const [isLoading, setIsLoading] = useState(true);
```
Comment (sehilyi) [inline src/ViewColumnBrush.js:30]: Thanks for adding this!

File: src/demo/CistromeExplorer.js [hunk 2]
```diff
@@ -27,9 +27,9 @@ const demos = {
         options: {
             rowInfoAttributes: [
                 {field: "Hierarchical Clustering (Average)", type: "tree", position: "left"},
-                {field: "qc_frip", type: "quantitative", position: "left"},
-                {field: "qc_fastqc", type: "quantitative", position: "left"},
-                {field: "Metadata URL", type: "url", position: "left", title: "cid"},
+                {field: "qc_frip", type: "quantitative", position: "left", title: "QC: FRIP"},
+                {field: "qc_fastqc", type: "quantitative", position: "left", title:  "QC: FastQC"},
+                {field: "cid", type: "comparison", position: "left", title: "Compare Positive and Negative"},
```
Comment (sehilyi) [inline src/demo/CistromeExplorer.js:32]: We could further generalize this track by having `domain` and `range` options:

```json
{..., "domain": ["positive", "negative"], "range": ["blue", "red"]}
```

In this way, colors for highlighting and texts for annotation can be defined by users. And clicking on a row multiple times will iterative through the elements defined in `domain`.

`range` can be an optional parameter, so if it is not defined by a user, we can internally use the color scheme that is being used for our `nominal` bar charts by default. 

By generalizing this, we can support other interesting functionalities, for example, allowing users to annotate samples based on their analysis results (e.g., "Worth further investigation").

File: src/demo/CistromeExplorer.js [hunk 3]
```diff
@@ -110,7 +108,7 @@ const demos = {
                 {field: "Hierarchical Clustering (Average)", type: "tree", position: "right"},
                 {field: "Random 3", type: "quantitative", position: "right"},
                 {field: ["Random 1", "Random 2", "Random 3", "Random 4"], type: "quantitative", position: "right"},
-                {field: "Metadata URL", type: "url", position: "right", title: "cid"},
+                {field: "Metadata URL", type: "url", position: "right", title: "Metadata URL"},
```
Comment (sehilyi) [inline src/demo/CistromeExplorer.js:111]: Having an option to set an alternative name to display in a track looks useful. But I think the usage of `title` is mixed between `url` type tracks and any other tracks. 

In the `url` type tracks, we were using the `title` option to set alternative names for **each sample**. For example, if `title` is set to `cid`, we were showing Cistrome IDs (e.g., `125`) instead of raw URLs (`http://dc2.cistrome.org/api/inspector?id=125`).

Since it can be misleading to use the same option for different usages depending on data types, I think we need to separate the options.

How about the following options?:
- `title`: show an alternative title of a track
- `alt`: show alternative names of individual urls

File: src/demo/CistromeExplorer.js (hunk 2 above)
Comment (sehilyi) [reply src/demo/CistromeExplorer.js:32]: Renaming `comparison` for the clarity: Since we can consider this track as a special case of `nominal` type bar chart (we show nominal data but it can be dynamically updated by users), how about a word that can express this? `nominal-dynamic` or `user-defined-nominal`?

File: src/ViewColumnBrush.js (hunk 1 above)
Comment (sehilyi) [inline src/ViewColumnBrush.js:30]: Thanks for adding this, this is useful!

File: src/TrackRowInfoVisDendrogram.js [hunk 4]
```diff
@@ -353,24 +352,24 @@ export default function TrackRowInfoVisDendrogram(props) {
...
-                    />
-                });
+            const mouseViewportX = d3.event.clientX;
+            const mouseViewportY = d3.event.clientY;
+
+            PubSub.publish(EVENT.TOOLTIP, {
+                x: mouseViewportX,
+                y: mouseViewportY,
+                content: <TooltipContent 
+                    title={(cannotAlign
```
Comment (sehilyi) [inline src/TrackRowInfoVisDendrogram.js:362]: I like this tooltip

File: src/TrackRowInfoVisComparison.js [hunk 5]
```diff
@@ -0,0 +1,233 @@
+import React, { useRef, useCallback, useEffect, useState } from "react";
```
Comment (sehilyi) [inline src/TrackRowInfoVisComparison.js:1]: An optional suggestion:

How about making this track visually similar to `nominal` type tracks and showing user-annotated categories (e.g., "Positive") as text labels? Initially, the bar can be gray as it is with a placeholder text (e.g., "Not selected"), and whenever a user clicks on a bar, the color and the text changes accordingly.

**Comment by sehilyi** [comment]
Great! I like this functionality which I think can be useful not only for the cistrome API but also for more general usage, e.g., annotating samples during data exploration.

I've left some comments to make this track generalizable, but open to any you opinion.

**Comment by sehilyi** [comment]
This also seems to fixe #269

File: src/demo/CistromeExplorer.js (hunk 3 above)
Comment (keller-mark) [reply src/demo/CistromeExplorer.js:111]: I like the `alt` idea

File: src/demo/CistromeExplorer.js (hunk 2 above)
Comment (keller-mark) [reply src/demo/CistromeExplorer.js]: I like `nominal-dynamic`

File: src/TrackRowInfoVisComparison.js (hunk 5 above)
Comment (keller-mark) [reply src/TrackRowInfoVisComparison.js]: This is a good idea, I have added as a separate issue https://github.com/hms-dbmi/cistrome-explorer/issues/303
